services:
  frontend:
    image: node:18
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "4200:4200"
    command: >
      sh -c "npm install && npx ng serve --host 0.0.0.0"
      
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"